### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by publicarray** [publicarray/solarsystem#1]
- [x] define 3 objectives
- [x] add spoken audio that matches textual descriptions - accessibility
- [x] [animation] add rings to Jupiter, Saturn, Uranus, and Neptune
- [ ] [animation] add intro tutorial to how to use the simulation
- [ ] [animation] add labels to the planets/ clickable planets
- [ ] [animation] add planet information/ facts
- [ ] [animation] add speed scale to animation
- [ ] [animation] add controls/presets to animation
- [ ] drag & drop quiz for sections
  - [x] solar system
  - [x] small bodies
  - [ ] planet types
- [x] Exam
- [x] ability to create your own model of the solar system.
- [x] CI & Tests
- [x] usability test
- [x] more accurate simulation by calculating orbital Inclination and planet Inclination
- [x] complete Rewrite in [threejs](https://github.com/mrdoob/three.js)
